version: "3.9"
services:
  server:
    build: ./server
    container_name: fastapi
    ports:
      - "80:80"
    volumes:
      - ./server/:/painting_style_classificator/server/
    command: uvicorn server:app --reload --host=0.0.0.0 --port=80


  client:
    build: ./client
    container_name: telegram_bot
    command: python main.py
    network_mode: host
    depends_on:
      - server