version: "3.9"
services:
  server:
    environment:
      - TG_TOKEN=${TG_TOKEN}
    build: ./server
    container_name: fastapi
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/painting_style_classificator/server/
    command: uvicorn server:app --reload --host=0.0.0.0 --port=5000


  client:
    environment:
      - TG_TOKEN=${TG_TOKEN}
    build: ./client
    container_name: telegram_bot
    command: python main.py
    network_mode: host
    depends_on:
      - server
